[project]
name = "data_cabin_quarto"
version = "0.1.0"
description = "Add a short description here"
authors = ["Gregory Power <31050507+gregorywaynepower@users.noreply.github.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = ">=3.12.4,<3.13"

[pypi-dependencies]
quarto-cli = ">=1.5.54, <1.6"
